# **
# author: leonardo.araujo@atos.net
# simple-cluster:
#	Arch:
#		mngt0-1 - mngt0-2
#			|
#		     client
#		  
#	Resources:
#	-> Pacemaker HA
#	-> Slurm
#	-> Clustershell
#
# **

cluster = {
	"mngt0-1" => { :ip => "10.0.0.1", :bmc => "10.100.0.1", :cpus => 1, :mem => 2048 },
	"mngt0-2" => { :ip => "10.0.0.2", :bmc => "10.100.0.2", :cpus => 1, :mem => 2048 }
}

client = {
	"node" => { :ip => "10.0.0.10", :bmc => "10.100.0.10", :cpus => 1, :mem => 1024}
}
# Cluster Core Setup:
Vagrant.configure("2") do |config|
	cluster.each_with_index do |(hostname, info), index|
		config.vm.define hostname do |mngt|
			mngt.vm.provider :virtualbox do |vb, override|
				config.vm.box = "jhcook/centos7"
				override.vm.network :private_network, ip: "#{info[:ip]}"
				override.vm.network :private_network, ip: "#{info[:bmc]}"
				override.vm.hostname = hostname
				vb.name = hostname
				vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
			end

			# Core Setup
			mngt.vm.provision :ansible do |ansible|
				ansible.playbook = 'provisioning/mngt.yml'
			end

			if hostname == 'mngt0-2'
				mngt.vm.provision :ansible do |ansible|
					ansible.limit = 'all'
					ansible.playbook = 'provisioning/ha.yml'
				end
			end
		end
	end

	client.each_with_index do |(hostname, info), index|
		config.vm.define hostname do |node|
			node.vm.provider :virtualbox do |vb, override|
				config.vm.box = "jhcook/centos7"
				override.vm.network :private_network, ip: "#{info[:ip]}"
				override.vm.network :private_network, ip: "#{info[:bmc]}"
				override.vm.hostname = hostname
				vb.name = hostname
				vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
			end

			node.vm.provision :ansible do |ansible|
				ansible.playbook = 'provisioning/client.yml'
			end

			# Slurm Setup after every VMs is UP
			if hostname == 'node'
				node.vm.provision :ansible do |ansible|
					ansible.limit = 'all'
					ansible.playbook = 'provisioning/slurm.yml'
				end
			end
		end
	end
end