---
- hosts: all
  become: yes
  tasks:
    - name: Remover firewalld
      yum: pkg=firewalld state=absent

    - name: Desabilitar Selinux
      lineinfile:
        path: /etc/selinux/config
        regexp: 'SELINUX=enforcing'
        line: 'SELINUX=disabled'


    - name: Update YUM
      yum: name=* state=latest update_cache=true
