---
- name: "create .ssh dir"
  file:
    path: "/home/vagrant/.ssh"
    state: directory
    
- name: "Add id_rsa.pub to authorized_keys"
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - files/id_rsa.pub

- name: "change file permissions"
  file: path={{ item.path }} mode={{ item.mode }}
  with_items:
    - { path: '/home/vagrant/.ssh/authorized_keys', mode: '600'}

- name: "change owner directory"
  file:
    path: "/home/vagrant/.ssh"
    owner: vagrant
    group: vagrant
    recurse: yes